---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  user: root

  roles:
    - common

# - name: configure and deploy the webservers and application code
#   hosts: pis
#   user: root

#   roles:
#     - web

# - name: deploy MySQL and configure the databases
#   hosts: dbservers
#   user: root

#   roles:
#     - db
