---

- name: Install vncserver
  apt: name=x11vnc state=installed

- name: Add github to known hosts
  template: src=known_hosts.j2 dest=/etc/ssh/ssh_known_hosts

- name: Clone noVNC repository
  git: repo=https://github.com/kanaka/noVNC.git
        dest=/usr/local/noVNC
        accept_hostkey=true

- name: Add noVNC initialize script
  copy: src=noVNC dest=/etc/init.d/noVNC mode=755

- name: Add noVNC launch script
  copy: src=launch.sh dest=/usr/local/noVNC/utils/launch.sh mode=755

- name: Add vnc to startup
  lineinfile: dest=/etc/xdg/lxsession/LXDE/autostart line='@bash /etc/init.d/noVNC start'