---
# This playbook contains common plays that will be run on all nodes.

- name: Updates apt before installing packages
  apt: update_cache=yes

- name: Install common cli utilities
  apt: name={{ item }} state=installed
  with_items:
   - vim
   - ack-grep
   - git
   - curl
   - build-essential
   - unclutter

- name: Setup motd
  template: src=motd.j2 dest=/etc/motd

# - name: Add vimrc
#   template: src=.vimrc.j2 dest={{ item.path }}
#             owner={{ item.owner }} group={{ item.group }}
#   with_items:
#     - { path: '/home/pi/.vimrc', owner: "{{ user }}", group: "{{ user }}" }
#     - { path: '/root/.vimrc', owner: 'root', group: 'root' }

- name: Add bashrc
  template: src=.bashrc.j2 dest={{ item.path }}
            owner={{ item.owner }} group={{ item.group }}
  with_items:
    - { path: '/home/{{ user }}/.bashrc', owner: "{{ user }}", group: "{{ user }}" }
    - { path: '/root/.bashrc', owner: 'root', group: 'root' }

# Add authorized users
- include: add_ssh_keys.yml

# Install vnc
- include: install_vnc.yml

# Turn off screen saver
- include: remove_screensaver.yml

# Add hostname
- include: add_hostname.yml

# - name: Install ntp
#   yum: name=ntp state=present
#   tags: ntp

# - name: Configure ntp file
#   template: src=ntp.conf.j2 dest=/etc/ntp.conf
#   tags: ntp
#   notify: restart ntp

# - name: Start the ntp service
#   service: name=ntpd state=started enabled=true
#   tags: ntp

# - name: test to see if selinux is running
#   command: getenforce
#   register: sestatus
#   changed_when: false
