---

- name: Install xscreensaver
  apt: name=xscreensaver state=installed

- name: Add xscreensaver
  copy: src=.xscreensaver dest={{ item.path }}
            owner={{ item.owner }} group={{ item.group }}
  with_items:
    - { path: '/home/{{ user }}/.xscreensaver', owner: "{{ user }}", group: "{{ user }}" }
    - { path: '/root/.xscreensaver', owner: 'root', group: 'root' }